# Generated by Django 5.0 on 2024-01-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ingrediants',
            new_name='ingredients',
        ),
    ]
